In [4]:
from glob import glob
import pandas as pd
import dask.dataframe as dd

In [5]:
pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', True)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_columns', 100)

In [6]:
def read_first_parquet(path):
    first_file = glob(path)[0]
    return pd.read_parquet(first_file)

## Real weather data

In [7]:
read_first_parquet('../data/weather_real/*/*/*.parquet').head()

  zip_code obs_geo_lat obs_geo_lng  obs_name  distance             timestamp day_ind  temp  feels_like  icon_extd  wx_icon wx_phrase  pressure  pressure_tend    pressure_desc  uv_index uv_desc  dewPt  heat_index    rh   vis   wc   wdir wdir_cardinal  gust  clds  wspd  precip_total  precip_hrly
0    27239       52.79        8.64  Diepholz      1040  2018-10-02T00:00:00Z       N   6.0         2.0     3300.0     33.0      Fair    1014.6            1.0           Rising         0     Low    4.0         6.0  88.0  55.0  2.0  270.0             W  22.0  None  18.0           NaN          NaN
1    49635       52.63        7.98  Diepholz       429  2018-10-02T00:00:00Z       N   6.0         2.0     3300.0     33.0      Fair    1014.6            1.0           Rising         0     Low    4.0         6.0  88.0  55.0  2.0  270.0             W  22.0  None  18.0           NaN          NaN
2    27239       52.79        8.64  Diepholz      1040  2018-10-02T01:00:00Z       N   6.0         2.0     3300.0     33.0      Fair    1014.4            2.0  Falling Rapidly         0     Low    3.0         6.0  85.0  65.0  2.0  260.0             W  25.0  None  18.0           NaN          NaN
3    49635       52.63        7.98  Diepholz       429  2018-10-02T01:00:00Z       N   6.0         2.0     3300.0     33.0      Fair    1014.4            2.0  Falling Rapidly         0     Low    3.0         6.0  85.0  65.0  2.0  260.0             W  25.0  None  18.0           NaN          NaN
4    27239       52.79        8.64  Diepholz      1040  2018-10-02T02:00:00Z       N   4.0         2.0     2600.0     26.0    Cloudy    1014.4            2.0          Falling         0     Low    3.0         4.0  88.0  50.0  2.0  230.0            SW  14.0  None  11.0           NaN          NaN

## Fake devices with geolocation

In [8]:
read_first_parquet('../data/device_geolocations_fake/1000_*.parquet').head()

                           gateway_uuid  geo_lat  geo_lng zip_code
0  ab1936e0-9f36-4ccc-a550-28c62b2d00ca  47.9751  11.7121    85635
1  e1d73013-385d-49a1-aa1b-749b9cf0f614  49.5878   7.4862    66885
2  d4a72194-3f2d-403e-a5b8-c3e0ab98fe8c  49.7468   7.4052    55743
3  f3fe4707-03dc-432a-8e49-6dca3c79f77d  49.4035  11.2714    90537
4  90dfd442-f3d8-403f-aec7-496fcd9aaba1  52.5601   9.3982    31535

## Fake features/events

In [9]:
read_first_parquet('../data/features_fake/*/*/*.parquet').head()

                           gateway_uuid             timestamp                          property     value  __index_level_0__
0  45bdde5d-d718-46c0-9f40-2fb7611f299e  2018-10-02T00:00:00Z  device.temperature.outside/value  5.200000                  0
1  f236cbfa-6d5a-4b2d-b2ee-897ca26c39bb  2018-10-02T00:00:00Z       device.water.pressure/value  1.542443                 27
2  3405cabf-1354-4faf-871a-c1ee66ccc8d8  2018-10-02T00:00:00Z       device.water.pressure/value  1.594311                 28
3  689fbf80-c3e3-4f38-bb65-e897a8d90ba5  2018-10-02T00:00:00Z       device.water.pressure/value  1.568610                 29
4  bf93b78b-aa01-4ed5-80b4-344ae96b07f4  2018-10-02T00:00:00Z       device.water.pressure/value  1.403069                 30